#!/bin/bash
#
# sparkle_sign.sh - Sign a release artifact (ZIP/DMG) for Sparkle
#
# This script signs a given ZIP or DMG file using the EdDSA private key
# stored in your Keychain (generated by sparkle_keygen.sh).
#
# Prerequisites:
#   - EdDSA keypair generated (run sparkle_keygen.sh first)
#   - Xcode with Sparkle SPM package (provides sign_update tool)
#   - Or: brew install sparkle
#
# Usage:
#   ./scripts/sparkle_sign.sh /path/to/MacSnap-1.0.2.zip
#
# Output:
#   Prints the EdDSA signature to use in appcast.xml sparkle:edSignature attribute
#

set -euo pipefail

if [ $# -lt 1 ]; then
    echo "Usage: $0 <path-to-zip-or-dmg>"
    echo ""
    echo "Example:"
    echo "  $0 ~/Desktop/MacSnap-1.0.2.zip"
    exit 1
fi

ARTIFACT_PATH="$1"

if [ ! -f "$ARTIFACT_PATH" ]; then
    echo "ERROR: File not found: $ARTIFACT_PATH"
    exit 1
fi

echo "=== Sparkle Artifact Signing ==="
echo ""
echo "Signing: $ARTIFACT_PATH"
echo ""

# Find sign_update tool
SIGN_UPDATE=""

if command -v sign_update &> /dev/null; then
    SIGN_UPDATE="sign_update"
elif [ -f "/usr/local/bin/sign_update" ]; then
    SIGN_UPDATE="/usr/local/bin/sign_update"
elif [ -d "$HOME/Library/Developer/Xcode/DerivedData" ]; then
    FOUND=$(find "$HOME/Library/Developer/Xcode/DerivedData" -name "sign_update" -type f 2>/dev/null | head -1)
    if [ -n "$FOUND" ]; then
        SIGN_UPDATE="$FOUND"
    fi
fi

if [ -z "$SIGN_UPDATE" ]; then
    echo "ERROR: Could not find 'sign_update' tool."
    echo ""
    echo "To install Sparkle tools, either:"
    echo "  1. Build the project in Xcode first (Sparkle package includes the tool)"
    echo "  2. Install via Homebrew: brew install sparkle"
    echo "  3. Download from: https://github.com/sparkle-project/Sparkle/releases"
    exit 1
fi

echo "Using sign_update at: $SIGN_UPDATE"
echo ""

# Sign the artifact
# The tool reads the private key from Keychain automatically
SIGNATURE=$("$SIGN_UPDATE" "$ARTIFACT_PATH")

echo "=== Signature ==="
echo ""
echo "$SIGNATURE"
echo ""
echo "Add this to your appcast.xml item's enclosure tag:"
echo "  sparkle:edSignature=\"...\""
echo ""
